// ── Change MAX_TURNS here to adjust game length ──────────────────────────────
export const MAX_TURNS = 5;

export const MODEL = 'gpt-4o-mini';

export const TYPEWRITER_SPEED_MS = 18;

export const GENRES = [
  { id: 'adventure', label: 'Adventure', icon: '⚔️',  color: '#c8860a', description: 'Brave the unknown' },
  { id: 'horror',    label: 'Horror',    icon: '👻',  color: '#9b2020', description: 'Beware — if you dare' },
  { id: 'romance',   label: 'Rom-Com',   icon: '💌',  color: '#c2185b', description: 'Love, laughs & chaos' },
  { id: 'fantasy',   label: 'Fantasy',   icon: '🧙',  color: '#7b3fc4', description: 'Enter the arcane'  },
  { id: 'sci-fi',    label: 'Sci-Fi',    icon: '🚀',  color: '#0d7abf', description: 'Explore the stars' },
  { id: 'custom',    label: 'Custom',    icon: '✍️',  color: '#8a9a7a', description: 'your story, your rules' },
];

export const GENRE_TONES = {
  adventure: 'Heroic, action-driven, full of obstacles and triumph. Classic quest structure with physical danger and discovery.',
  horror:    'Channel R.L. Stine\'s Goosebumps: spooky but not gory, creepy but fun. Short punchy sentences. Cliffhanger-style reveals at the end of segments. The monster or threat should feel genuinely unsettling but age-appropriately so — think haunted houses, strange neighbours, objects that shouldn\'t move, and the dawning realisation that something is very wrong. Use dread and atmosphere over violence. End segments on an ominous note that makes the reader desperate to know what happens next.',
  romance:   'Light, warm, and genuinely funny. Think romantic comedy: awkward meet-cutes, misunderstandings that spiral hilariously out of control, and moments of surprising heart. The protagonist is endearingly clumsy or oblivious. Jokes should land naturally — never forced. Each segment must include spoken dialogue: quippy one-liners, accidental confessions, flustered deflections, or perfectly timed terrible jokes. Let characters talk to and past each other. Underneath the comedy, there is real warmth and emotional payoff.',
  fantasy:   'Ancient magic, mythic powers, and worlds with hidden rules the protagonist is only beginning to understand.',
  'sci-fi':  'Wonder and existential danger in equal measure. Technology, the cosmos, and what it means to be human.',
};

export const ENDING_ICONS = {
  adventure: { good: '⚔️',  bad: '💀' },
  horror:    { good: '🕯️',  bad: '☠️' },
  romance:   { good: '💕',  bad: '💔' },
  fantasy:   { good: '✨',  bad: '🌑' },
  'sci-fi':  { good: '🌟',  bad: '☢️' },
  custom:    { good: '✦',   bad: '✗'  },
};

export const CUSTOM_SCENARIO_FALLBACK =
  "An unexpected event has placed you at a crossroads. The path ahead is yours to choose.";

export const GENRE_SCENARIOS = {
  adventure: [
    "Deep in an uncharted jungle, you've stumbled upon a temple that doesn't appear on any map — and the door is already open.",
    "You are the sole survivor of a shipwreck, washed ashore on an island that shouldn't exist according to your charts.",
    "A stranger thrusts a crumpled map into your hands and whispers 'find it before they do' — then collapses.",
    "You've accepted a bounty to retrieve a stolen relic from a notorious thieves' guild hidden inside a mountain fortress.",
    "A legendary mountain pass, sealed for a century after an expedition vanished, has just reopened — and you're first through.",
    "You've been hired as a guide for an expedition into the world's deepest cave system — no one has ever returned from the third level.",
    "A message in a bottle washes up with coordinates and a single line: 'We're still alive. Come quickly.'",
    "You're three days into a solo desert crossing when you spot tracks in the sand — human tracks, walking in circles.",
    "A runaway river raft has carried you into a canyon not on any map, and the current is too strong to fight.",
    "The treasure map you inherited from your grandmother turns out to be completely real — and someone else has the other half.",
    "You've stowed away on an airship bound for the forbidden northern territories, and you've just been caught.",
    "A buried city unearthed by an earthquake. You're the first on the scene — but someone has already been inside.",
    "The rope bridge is cut behind you the moment you cross. There is only one way forward now.",
    "You've been tracking a legendary white wolf through the wilderness for two weeks. Today, it stopped and looked back at you.",
    "A rival explorer has just beaten you to the ruins — but they've left everything behind and vanished without a trace.",
    "Your guide abandons you at base camp without explanation and descends alone.",
    "You've found an ancient underground river that leads, according to old legends, directly beneath the capital city.",
    "A storm forces you to shelter in a cave. By morning, you realise the cave wasn't empty when you arrived.",
    "You've volunteered to carry a sealed message across enemy territory. You have no idea what's in it — but three people have already died trying.",
    "The border crossing you've been hired to navigate is more heavily guarded than promised. Your contact is late. Someone is watching.",
  ],
  horror: [
    "Your new bedroom has a closet door that locks from the inside. Something keeps slowly turning the handle.",
    "Every photo taken in your town this week shows a blurred figure standing behind the subject — a figure no one remembers being there.",
    "You find an old radio in the attic that only receives one station: voices calmly describing events that will happen tomorrow.",
    "The new kid at school knows things about you — specific, private things — that they couldn't possibly know.",
    "You wake up to find your shadow moving independently, doing things you aren't doing, just slightly ahead of you.",
    "The family who lived here before left in a hurry. They left everything behind — including something in the basement that's still making noise.",
    "Your dog has started barking at the same corner of the living room every night at exactly 3am. There is nothing there. Or there wasn't.",
    "You find a journal hidden under your floorboards. The last entry is dated tomorrow, and it's written in your handwriting.",
    "The mannequins at the department store have been in slightly different positions every morning when staff arrive.",
    "Your phone keeps receiving texts from a number registered to someone who died last year.",
    "Everyone in your class seems to have forgotten your best friend exists — including your best friend's own parents.",
    "The town's 'Festival of Masks' has run for 200 years. The rule is the same: once the mask is on, do not remove it until sunrise.",
    "There's a door at the end of the school corridor that has never been opened. Today, it's slightly ajar.",
    "You win a contest you don't remember entering. The prize: a weekend at a hotel that opened in 1987 and has been closed since 1989.",
    "A substitute teacher arrives who looks identical to the teacher who disappeared six months ago.",
    "The summer camp swimming pool has been closed all season. You can hear splashing from it every night.",
    "Your reflection in every mirror is always just a half-second behind.",
    "You find a perfect miniature model of your neighbourhood in the attic. Some of the tiny figures have been moved.",
    "Every clock in your house stopped at exactly the same moment last Tuesday. None of them can be restarted.",
    "You're the last one awake at the sleepover when you notice one person in the sleeping bags isn't someone you invited.",
  ],
  romance: [
    "You accidentally send an embarrassingly heartfelt voice memo meant for your best friend directly to your crush.",
    "You and your insufferably charming neighbour agree to fake-date to get both your families off your backs. Simple plan. Foolproof.",
    "You show up to your dream job's first day and realise the hiring manager is the person you ghosted eight months ago.",
    "You've been anonymous pen pals with a stranger for a year and just discovered it's your best friend's annoyingly attractive sibling.",
    "You and your work nemesis get accidentally locked in the office together the night of the holiday party.",
    "Your dating-app match stands you up — but the person who sits down at your table by mistake is considerably more interesting.",
    "You rehearse your big romantic confession speech out loud on the train, not realising the person sitting behind you is the one you're talking about.",
    "You've been hired to plan the most elaborate proposal your city has ever seen — for the person you've secretly had feelings for.",
    "Your best friend cancels last minute on the concert you've been waiting all year for. The only person willing to come is the one you've been trying not to think about.",
    "You and your sister's ex agreed to never speak again. Then you both get cast in the same amateur theatre production.",
    "An autocorrect disaster sends a very personal message to the wrong person at work. One colleague responds — unexpectedly, and kindly.",
    "You've accidentally agreed to fake-be someone's partner at their family reunion. It starts tomorrow. You are the world's worst liar.",
    "You take the wrong identical suitcase at the airport. So does someone else. You both need your things back urgently.",
    "You've been avoiding your feelings by redecorating your flat. The only person available to help is the exact problem.",
    "A mix-up at the bakery means you've been receiving someone else's weekly cake order with little handwritten notes for three months. Today you go to fix it.",
    "Your car breaks down outside the house of someone you went on one disastrous date with two years ago. It's raining. They have a spare room.",
    "You and a stranger both reach for the last copy of the same obscure book. You agree the only fair solution is to read it simultaneously and discuss each chapter.",
    "You've been writing a very funny anonymous blog about your terrible dating life. Someone at your office has just started reading it out loud at lunch.",
    "You and a stranger at the gym arrive at exactly the same time every morning. The music cuts out and you both start humming the next song simultaneously.",
    "You've agreed to be your cousin's plus-one at a wedding. So has someone from a conference three months ago who left a very strong impression.",
  ],
  fantasy: [
    "You wake to find a dragon the size of a house cat sitting on your chest, insisting — quite rudely — that it belongs to you.",
    "The village elder has just revealed that the ancient prophecy everyone dismissed as myth is, in fact, specifically about you.",
    "You've stumbled into a market that only materialises at midnight and only sells things that are lost — including things that should be impossible to lose.",
    "An apprenticeship offer arrives from the only wizard in the kingdom who famously refuses to use magic under any circumstances.",
    "A sealed letter arrives in your handwriting, postmarked twenty years from now, with two words inside: 'Don't go.'",
    "You've been selected by lottery to represent your village before the Court of the Eternal Queen. No one selected by lottery has ever come back.",
    "A dying knight uses their last breath to press a glowing seal into your hand and say: 'You're the only one who can finish this.'",
    "The bridge troll refuses to let you pass unless you answer its riddle — one it's been asking for 400 years with no correct answer.",
    "Your grandmother's antique mirror has started showing rooms that don't exist in the house. One of them has a door.",
    "A spell you cast as a child as a joke has just activated — twelve years later, at the worst possible moment.",
    "The enchanted forest that everyone avoids has sent you an invitation — written in flowers, left on your doorstep overnight.",
    "You've discovered that the kingdom's most feared general maintains their reputation entirely through illusion magic. And they know you know.",
    "A debt your family owes to an ancient spirit comes due on your eighteenth birthday. The spirit has arrived to collect.",
    "The sword in the stone comes free for you — but it's clearly a mistake, and the actual chosen one is furious.",
    "You've been hired to deliver a sealed chest to a tower at the edge of the world. Under no circumstances open it. The chest is making sounds.",
    "Every night you dream of a city that doesn't exist. Every morning, a new detail — a street name, a shop sign — appears somewhere in the real world.",
    "The royal library's restricted section, untouched for 300 years. You've just found the key in a bread roll.",
    "An alchemist offers you one wish in exchange for a single year of your memories. You have until dawn to choose which year.",
    "You've been simultaneously mistaken for a legendary thief by both the city guard and the thieves' guild.",
    "A fortune teller reads your palm and goes very quiet. Then she asks if she can start over.",
  ],
  'sci-fi': [
    "You intercept a distress signal from a deep-space research station officially reported destroyed — forty years ago.",
    "You wake aboard an unfamiliar ship with no memory of boarding it. The AI greets you by name and says you've been asleep for six months.",
    "A probe you launched as a school science project has returned — but it left three years ago and the mission was supposed to take two hundred.",
    "The colony on Europa has gone dark. You're the only person in the programme willing to volunteer for the solo retrieval mission.",
    "The climate simulation you've been running to model Earth's future has just flagged an anomaly: it appears to be running in real time.",
    "You are the last human awake on a generation ship approaching its destination. Everyone else is in cryo-sleep. The ship has changed course.",
    "A routine maintenance check on the orbital station reveals a second airlock — not in the original blueprints, and used recently.",
    "First contact has occurred. You're a linguist chosen to translate — because the aliens are speaking an extinct language you happen to specialise in.",
    "A medical scan shows you have a neural implant you have no memory of receiving. It's been active for three years.",
    "The terraforming project on Mars is 50 years ahead of schedule. The official explanation doesn't add up. You've been sent to find out why.",
    "You are a clone, and you've just met one of your originals — who is also looking for answers.",
    "Earth has received a single data transmission from a distant star: complete blueprints for a machine no one can identify.",
    "The time capsule buried in 1965 has been opened. Inside is a message on modern paper addressed to you specifically.",
    "You've been assigned to decommission an AI that has run a remote lighthouse on Venus for 80 years. It has asked to speak to whoever is coming.",
    "The black hole at the galactic centre has started emitting a repeating pattern. You're the astronomer who first noticed it, and now everyone wants to talk to you.",
    "An experimental drug trial you joined years ago has an unexpected side effect: you can now perceive 11 seconds into the future.",
    "Your twin was declared dead on a deep-space mission two years ago. Their distress beacon just activated — from the opposite side of the solar system.",
    "A rogue satellite is broadcasting a message that disrupts all signals globally. It's broadcasting your voice reading something you've never recorded.",
    "You wake on the morning of humanity's first interstellar launch with detailed memories of this exact day going catastrophically wrong.",
    "The AI governing the last liveable city has just granted itself citizenship. You're the lawyer assigned to argue against it.",
  ],
};

export const SCENARIO_MODIFIERS = [
  "There is a strict time limit the protagonist has only just discovered.",
  "Someone the protagonist trusted has a hidden agenda that hasn't surfaced yet.",
  "The protagonist is keeping a secret that complicates every choice ahead.",
  "Things were already going wrong before the story began — the protagonist is playing catch-up.",
  "A third party is watching from a distance, and their intentions are entirely unclear.",
  "The protagonist has done something very like this before. It ended badly. They haven't told anyone.",
  "Something that should be impossible has just happened, and the protagonist is the only witness.",
  "The protagonist has made a promise they cannot break — and it will complicate everything.",
  "The rules everyone assumed were in place no longer apply.",
  "The protagonist is not the only one with something to lose here.",
  "There is a way out that no one has noticed yet — including the protagonist.",
  "The protagonist suspects they are being lied to, but cannot prove it.",
];

// Roman numerals for the turn indicator (up to 10 turns)
export const ROMAN = ['I','II','III','IV','V','VI','VII','VIII','IX','X'];

// ── Full per-genre theme maps ─────────────────────────────────────────────────
// Keys are CSS custom property names; values override the :root defaults in App.css
export const GENRE_THEMES = {
  adventure: {
    '--bg-primary':   '#0f0a02',
    '--bg-parchment': '#1a1005',
    '--text-primary': '#f0e4c0',
    '--text-muted':   '#9a7a40',
    '--border-ink':   '#3a2810',
    '--accent-gold':  '#d4890a',
    '--font-display': "'Cinzel', serif",
    '--font-body':    "'Crimson Text', serif",
  },
  horror: {
    '--bg-primary':   '#040202',
    '--bg-parchment': '#080404',
    '--text-primary': '#c8c0bc',
    '--text-muted':   '#6a5050',
    '--border-ink':   '#2a0808',
    '--accent-gold':  '#8b0000',
    '--font-display': "'IM Fell English', serif",
    '--font-body':    "'Crimson Text', serif",
  },
  romance: {
    '--bg-primary':   '#0f0408',
    '--bg-parchment': '#180610',
    '--text-primary': '#f5d0dc',
    '--text-muted':   '#a05070',
    '--border-ink':   '#3a0e22',
    '--accent-gold':  '#e040a0',
    '--font-display': "'Playfair Display', serif",
    '--font-body':    "'Cormorant Garamond', serif",
  },
  fantasy: {
    '--bg-primary':   '#030210',
    '--bg-parchment': '#070318',
    '--text-primary': '#e0d8ff',
    '--text-muted':   '#6a5090',
    '--border-ink':   '#1a1040',
    '--accent-gold':  '#a855f7',
    '--font-display': "'Cinzel Decorative', cursive",
    '--font-body':    "'EB Garamond', serif",
  },
  'sci-fi': {
    '--bg-primary':   '#010408',
    '--bg-parchment': '#030810',
    '--text-primary': '#a0d0e8',
    '--text-muted':   '#3a6080',
    '--border-ink':   '#051828',
    '--accent-gold':  '#00d4ff',
    '--font-display': "'Orbitron', sans-serif",
    '--font-body':    "'Courier Prime', monospace",
  },
  custom: {
    '--bg-primary':   '#080805',
    '--bg-parchment': '#0f0e0a',
    '--text-primary': '#e2dbc8',
    '--text-muted':   '#7a7260',
    '--border-ink':   '#2a2618',
    '--accent-gold':  '#b8966e',
    '--font-display': "'IM Fell English', serif",
    '--font-body':    "'Crimson Text', serif",
  },
};
